hmpps-auth:
  url: "http://localhost:8090/auth"



spring:
  application:
    name: hmpps-prisoner-finance-holds-api

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER:localhost:5436}/${DB_NAME:holds}?sslmode=prefer'
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

general-ledger-api:
  url: ${GENERAL_LEDGER_API_URL:http://localhost:8084}
  client:
    id: ${GENERAL_LEDGER_API_CLIENT_ID:hmpps-prisoner-finance-general-ledger-api}
    secret: ${GENERAL_LEDGER_API_CLIENT_ID:clientsecret}