-- Data dictionary for the holds schema.
--
-- These comments are read by SchemaSpy (published to GitHub Pages) and by anything else that reads
-- pg_description, including the CSV export for the MOJ Data Catalogue / Glue. Keep them updated when
-- columns are added or their meaning changes - SchemaCommentsTest fails the build if a table or column
-- has no comment.
--
-- Every column comment ends with a sensitivity classification:
--
--   [Sensitivity: NONE]                - not personal data in itself (keys, timestamps, process flags,
--                                        and the reference data in the constant_* tables)
--   [Sensitivity: PERSONAL]            - personal data about a prisoner: identifies or locates them
--   [Sensitivity: STAFF]               - personal data about a member of staff, typically the username
--                                        that performed an action
--   [Sensitivity: SPECIAL-CATEGORY]    - UK GDPR Article 9 data (health, sexuality, religion, race,
--                                        gender reassignment) or criminal offence data under Article 10
--   [Sensitivity: OFFICIAL-SENSITIVE]  - not personal data, but damaging if disclosed
--
-- STAFF is still personal data and still in scope for a staff member's own subject access request. It is
-- separated from PERSONAL so that an extract about prisoners can be reasoned about without staff columns
-- inflating the count, and so staff data can be dropped or pseudonymised independently.
--
-- Four things to understand before using these classifications:
--
--   1. They describe the column's own content, not the row's. This schema describes a record about a
--      financial hold of money placed on a prisoners trust account, not people, so almost everything
--      here is about a financial action. This is exactly why the handful of columns that can identify
--      an individual, be combined to place that individual at a location or be combined to identify
--      an amount of money an individual may or has received, matter.
--
--   3. **Every free-text column should be assumed to contain more than its question asks.** A field
--      asking for a description of the hold may contain details of an incident as a reason for the
--      holding of money which may be used to record which prisoner or staff member was involved. Free
--      text is classified on what people actually write in it, not on the field label.
--

------------------------------------------------------------------------------------------------
-- holds - the record describing a hold itself
------------------------------------------------------------------------------------------------

COMMENT ON TABLE holds IS 'A record of a financial hold of money placed on a prisoners trust account by a prison.';

COMMENT ON COLUMN holds.id IS 'Primary key. A UUIDv7 generated by the application, used as the hold''s permanent public identifier across DPS. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.prison_number IS 'NOMIS offender number (prison number/noms number) of the prisoner that the money has been held from. The link that makes every row here personal data about that prisoner. Updated in place when NOMIS merges two offender records. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN holds.sub_account_ref IS 'The reference used to identify the prisoner sub account of their trust account where the money is being held from - CASH, SPENDS, SAVINGS. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.legacy_hold_number IS 'NOMIS hold number, allowing these records to be linked back to the original source record held in NOMIS. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.hold_location IS 'Prison code, such as MDI, where the money from the prisoner is being held. Read with prison_number it indicates where that prisoner was held at the time. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN holds.hold_from_date IS 'When the money was held from the prisoner. Null if this is not yet released. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.hold_until_date IS 'When the money is expected to be released back to the prisoner. Null if this is open ended. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.hold_type IS 'What kind of hold this is - HOLD or WITHHOLD. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.description IS 'Free text description about the hold. Free text: assume it can name an incident, prisoner, staff member or member of the public, for example when explaining who sent the money that has been held by the prison or the incident that resulted in the money being held. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN holds.amount IS 'The amount of money that is/was held from the prisoner. [Sensitivity: OFFICIAL-SENSITIVE]';
COMMENT ON COLUMN holds.created_at IS 'When this hold record was first created. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.created_by IS 'DPS username of the person who recorded the hold by the prison. [Sensitivity: STAFF]';
COMMENT ON COLUMN holds.HOLD_TRANSACTION_ID IS 'The unique identifier of the prisoner finance general ledger transaction that took the money from the prisoner, allowing these records to be linked back to the financial records held within the general ledger of accounts. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.is_released IS 'A flag indicating whether the money has been released back to the prisoner. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.released_at IS 'When the money was released back to the prisoner. Null if the money has not yet been released. [Sensitivity: NONE]';
COMMENT ON COLUMN holds.RELEASE_TRANSACTION_ID IS 'The unique identifier of the prisoner finance general ledger transaction that returned the money to the prisoner, allowing these records to be linked back to the financial records held within the general ledger of accounts. [Sensitivity: NONE]';
